-- How each item helps the specific business in front of the rep.
-- Its own migration: the previous one has already shipped, and editing an
-- applied migration changes its checksum, which makes prisma migrate deploy
-- fail and blocks every deploy after it.
-- Only fills blanks, so a line edited in the database is never overwritten.
ALTER TABLE "sales_playbook_items" ADD COLUMN IF NOT EXISTS "benefit" TEXT NOT NULL DEFAULT '';

UPDATE "sales_playbook_items" SET "benefit" = 'More of the people already finding {company} turn into actual enquiries. Same marketing, same traffic, more jobs — which is why it comes before spending a penny more on getting found.' WHERE "slug" = 'websiteredesign' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'The customers reaching {company} from a phone — which will be most of them — can actually get in touch without pinching and zooming. It also stops Google quietly ranking {company} lower for a bad phone experience.' WHERE "slug" = 'mobileoptimisation' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Each thing {company} does gets its own page, so someone searching for that exact job finds {company} instead of a competitor who happens to have a page for it.' WHERE "slug" = 'servicepagestructure' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Enquiries arrive at {company} ready to quote instead of as ''call me''. That''s a couple of phone calls saved on every single job, and quotes going out same-day rather than three days later.' WHERE "slug" = 'qualifiedenquiryform' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company} stops losing the evening and weekend enquiries entirely. Those people aren''t waiting until Monday — they''re ringing the next name on the list tonight.' WHERE "slug" = 'bookingorestimateworkflow' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company} shows up in the map results when someone nearby searches. That''s the readiest-to-buy customer there is, and right now they''re finding somebody else.' WHERE "slug" = 'localseo' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company} finally knows which marketing actually produces work. That usually means cutting something that was never paying and putting the money where it does.' WHERE "slug" = 'analyticssetup' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'No enquiry to {company} gets lost in somebody''s inbox again. Following up stops depending on whoever happens to remember.' WHERE "slug" = 'crmleadrouting' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'The words speak to what {company}''s customers are actually worried about, so a bigger share of the same visitors get in touch. It lifts every other thing on this list.' WHERE "slug" = 'professionalcopywriting' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s reviews, guarantees and real job photos appear exactly where someone hesitates. The reputation already exists — this just stops it being invisible at the deciding moment.' WHERE "slug" = 'trustandproofsystem' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s customers can check their own quote, job and paperwork instead of ringing to ask. It removes a whole category of unpaid admin, and makes {company} look considerably bigger than the competition.' WHERE "slug" = 'customerportal' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Every completed job for {company} turns into a review request automatically, and unhappy customers get routed privately first. More reviews means better ranking and an easier sell on every future job.' WHERE "slug" = 'reviewautomation' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Fewer no-shows for {company}, and quotes that went quiet get a nudge without anyone remembering to send it. Texts get read in minutes; emails often don''t get read at all.' WHERE "slug" = 'smsfollowup' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company} takes the deposit the moment someone says yes, rather than invoicing and waiting. Better cash flow, and far fewer people going cold between agreeing and paying.' WHERE "slug" = 'onlinepayments' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Some of {company}''s one-off customers become monthly income. That''s what makes a quiet month survivable and what makes the business worth more if it''s ever sold.' WHERE "slug" = 'recurringserviceplans' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'The enquiries {company} didn''t win aren''t written off — they hear from {company} occasionally, so a slice of them come back later at no extra cost to acquire.' WHERE "slug" = 'emailnurture' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'If {company} runs ads, more of that budget turns into enquiries instead of bouncing off a general page. It makes money already being spent work harder.' WHERE "slug" = 'paidsearchlandingpages' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Customers send photos of the problem with the enquiry, so {company} can often quote without driving out. Every avoided site visit is hours back.' WHERE "slug" = 'photoanddocumentuploads' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s happy customers become a steady source of new ones. Referred work costs nothing to win and closes far more easily than cold enquiries.' WHERE "slug" = 'referralworkflow' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s site keeps improving rather than slowly falling behind, and there''s a monthly report showing what changed and what it did.' WHERE "slug" = 'ongoinggrowthplan' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s buyers can work out what they need themselves, the way technical buyers actually prefer to. Right now the ones who can''t figure it out just leave, and {company} never even knows they existed.' WHERE "slug" = 'productledwebsiteredesign' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'The sizing conversation {company}''s engineers currently have over email happens automatically. Buyers reach the right product with confidence, and engineering time goes to real opportunities instead of tyre-kickers.' WHERE "slug" = 'guidedselectionsystem' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Quote requests reach {company} complete — specifications, quantities, deadlines, drawings — so quoting starts immediately instead of after a week of chasing. Faster quotes win more of them.' WHERE "slug" = 'structuredrfqwebapp' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Drawings and parts lists arrive with the enquiry rather than in a chain of emails, so {company} can start quoting the same day. Handling them properly also matters to bigger buyers doing due diligence.' WHERE "slug" = 'securefileupload' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Every enquiry becomes a tracked opportunity for {company} automatically, with the product interest attached. {company} can finally see conversion by product line instead of guessing at it.' WHERE "slug" = 'crmintegration' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company} sees which products get attention, where buyers give up, and which enquiries become orders — so marketing spend follows the lines that actually sell.' WHERE "slug" = 'analyticsandfunneltracking' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company} gets found for the specific technical terms buyers search. It''s a small number of visitors, but in this industry one of them can be worth more than the entire project.' WHERE "slug" = 'technicalseo' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s team can keep product information current without paying a developer for every change. It''s the item that stops the site going stale in six months.' WHERE "slug" = 'cmsanddatamigration' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s systems stop needing the same information typed into them twice, and the numbers stop disagreeing between them. Less admin, and figures people can actually trust.' WHERE "slug" = 'coreintegrations' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company} meets the standards larger and public-sector buyers increasingly ask about in procurement. Cheap now, expensive to retrofit, and it protects deals rather than just reducing risk.' WHERE "slug" = 'accessibilityandprivacy' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s customers can see where their quote is without ringing to ask. It removes the chasing calls and makes {company} look far more organised than competitors who can''t offer it.' WHERE "slug" = 'quotestatusdashboard' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s distributors and reps get what they need themselves instead of emailing head office. Better-equipped partners sell more, and the internal interruptions stop.' WHERE "slug" = 'distributororrepportal' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Engineers buying from {company} can save a configuration and come back to it. Technical purchases take weeks — losing their work between visits is a common reason they end up buying elsewhere.' WHERE "slug" = 'savedprojectsandboms' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s existing customers reorder parts themselves. That''s the highest-margin revenue there is, and it stops being capped by how many calls the team can answer.' WHERE "slug" = 'partsandrepeatordering' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Service requests to {company} get logged and tracked rather than lost in email, and {company} gets data on which products generate the most support load.' WHERE "slug" = 'serviceandsupportdashboard' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'What {company}''s customers see reflects what''s actually available, so quotes stop going out on stock that isn''t there. It''s what makes everything else on the site trustworthy.' WHERE "slug" = 'erporinventoryintegration' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s buyers can get themselves up to speed without hand-holding, which shortens the sale and cuts the same technical questions being answered over and over.' WHERE "slug" = 'trainingandresourceplatform' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company} gets prompted in front of customers at the moments that matter — a quote gone quiet, a service due, parts likely needing reordering. This is revenue {company} has already earned the right to.' WHERE "slug" = 'automatedlifecyclemessaging' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Only worth it if {company}''s people or customers work somewhere a browser struggles — on site, offline, in a workshop. Where that''s true it changes how they work; where it isn''t, that budget belongs in the core build.' WHERE "slug" = 'nativeormultiplatformapp' AND "benefit" = '';
