import type { NextRequest } from 'next/server';
import { prisma } from '@/lib/prisma';

/**
 * Brute-force protection for the sign-in forms.
 *
 * Neither login route had any throttling: an attacker could try passwords as
 * fast as the network allowed, forever. That matters more here than in most
 * apps because client passwords are generated by the studio and emailed, and
 * in practice nobody changes them — they are permanent credentials guarding
 * real project data.
 *
 * Two independent limits, because they catch different attacks:
 *
 *   - per identifier, to stop someone grinding one known account
 *   - per IP, to stop credential stuffing sprayed across many accounts, which
 *     would never trip a per-account limit
 *
 * State lives in Postgres rather than in memory. On serverless an in-memory
 * counter resets on every cold start and is not shared across instances, so an
 * attacker simply gets unlimited "first" attempts — which is barely better
 * than nothing while looking like a control.
 */

const WINDOW_MS = 15 * 60 * 1000;
const MAX_PER_IDENTIFIER = 8;
const MAX_PER_IP = 30;

export function clientIp(request: NextRequest): string {
  const forwarded = request.headers.get('x-forwarded-for');
  return forwarded?.split(',')[0]?.trim() || request.headers.get('x-real-ip') || 'unknown';
}

export type LoginGuard =
  | { allowed: true }
  | { allowed: false; retryAfterSeconds: number };

/**
 * Whether this sign-in attempt may proceed.
 *
 * Fails OPEN if the database is unreachable. That is a deliberate trade: a
 * throttle that locks the studio out of its own dashboard during a database
 * blip causes a certain outage to prevent a hypothetical attack. The failure
 * is logged loudly so it is not silent.
 */
export async function checkLoginAllowed(
  identifier: string,
  ip: string
): Promise<LoginGuard> {
  const since = new Date(Date.now() - WINDOW_MS);
  const key = identifier.trim().toLowerCase();

  try {
    const [byIdentifier, byIp] = await Promise.all([
      prisma.loginAttempt.count({ where: { identifier: key, createdAt: { gte: since } } }),
      prisma.loginAttempt.count({ where: { ip, createdAt: { gte: since } } }),
    ]);

    if (byIdentifier >= MAX_PER_IDENTIFIER || byIp >= MAX_PER_IP) {
      return { allowed: false, retryAfterSeconds: Math.ceil(WINDOW_MS / 1000) };
    }

    return { allowed: true };
  } catch (error) {
    console.error('[login-guard] check failed, allowing attempt:', error);
    return { allowed: true };
  }
}

/** Record a failure. Never throws — a logging problem must not break login. */
export async function recordFailedLogin(identifier: string, ip: string): Promise<void> {
  try {
    await prisma.loginAttempt.create({
      data: { identifier: identifier.trim().toLowerCase(), ip },
    });

    // Opportunistic cleanup so the table cannot grow without bound. Cheap,
    // indexed, and saves needing a scheduled job for one small table.
    if (Math.random() < 0.05) {
      await prisma.loginAttempt.deleteMany({
        where: { createdAt: { lt: new Date(Date.now() - WINDOW_MS) } },
      });
    }
  } catch (error) {
    console.error('[login-guard] could not record failure:', error);
  }
}

/** A successful sign-in clears that account's failures. */
export async function clearFailedLogins(identifier: string): Promise<void> {
  try {
    await prisma.loginAttempt.deleteMany({
      where: { identifier: identifier.trim().toLowerCase() },
    });
  } catch (error) {
    console.error('[login-guard] could not clear failures:', error);
  }
}

/** The response body every throttled attempt gets. */
export function tooManyAttempts(retryAfterSeconds: number) {
  return Response.json(
    { error: 'Too many sign-in attempts. Please try again in a few minutes.' },
    { status: 429, headers: { 'Retry-After': String(retryAfterSeconds) } }
  );
}
