import { buildContractPdf } from '@/lib/contract-pdf';
import { buildContractSections, toContractCustomItems } from '@/lib/contract-terms';
import { buildInvoiceForProposal, type InvoiceForProposalInput } from '@/lib/invoice-pdf';
import {
  ADD_ONS,
  BASE_SERVICES,
  CLIENT_TYPES,
  DEPOSIT_PERCENT,
  TIMELINES,
  calculatePrice,
  customItemsTotal,
  depositAmount,
  formatCents,
} from '@/lib/pricing';

/**
 * The two documents a proposal produces, built from one selection.
 *
 * The contract used to be assembled inline in the "download contract" route
 * and nowhere else, so the sign-and-pay email — the one send that actually
 * matters — went out with an invoice and no agreement. Building both here
 * means the copy a client is emailed and the copy a rep downloads are
 * generated by the same code from the same numbers, rather than by two
 * routes that have to be kept in step by hand.
 */

/** Same inputs the invoice needs; the contract needs nothing more. */
export type ProposalDocumentInput = InvoiceForProposalInput;

export async function buildContractForProposal(
  input: ProposalDocumentInput
): Promise<Uint8Array> {
  const { company, contactName, baseService, addOnKeys, clientType, timeline, customItems, totalPrice } =
    input;

  const breakdown = calculatePrice({ baseService, addOns: addOnKeys, clientType, timeline });
  const customTotal = customItemsTotal(customItems);
  const serviceLabel = BASE_SERVICES[baseService].label;
  const addOnLabels = [
    ...addOnKeys.map((k) => ADD_ONS[k].label),
    ...customItems.map((c) => `${c.label} (${formatCents(c.priceCents)})`),
  ];
  // The persisted total, not the recalculated one — a negotiated price that
  // was agreed must not be quietly restated by the contract that formalises
  // it.
  const deposit = depositAmount(totalPrice);
  const timelineLabel = `${TIMELINES[timeline].label} (${TIMELINES[timeline].weeks})`;

  const sections = buildContractSections({
    company,
    contactName,
    serviceLabel,
    serviceDescription: BASE_SERVICES[baseService].description,
    addOnLabels,
    addOnKeys,
    customItems: toContractCustomItems(customItems),
    baseServiceKey: baseService,
    clientTypeKey: clientType,
    timelineKey: timeline,
    timelineLabel,
    clientTypeLabel: CLIENT_TYPES[clientType].label,
    basePrice: formatCents(breakdown.basePrice),
    addOnsPrice: formatCents(breakdown.addOnsPrice + customTotal),
    totalPrice: formatCents(totalPrice),
    depositAmount: formatCents(deposit),
    balanceAmount: formatCents(totalPrice - deposit),
    depositPercent: DEPOSIT_PERCENT,
    effectiveDate: new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    }),
  });

  return buildContractPdf({
    company,
    contactName,
    serviceLabel,
    addOnLabels,
    customItems: toContractCustomItems(customItems),
    timelineLabel,
    basePrice: formatCents(breakdown.basePrice),
    addOnsPrice: formatCents(breakdown.addOnsPrice + customTotal),
    totalPrice: formatCents(totalPrice),
    depositAmount: formatCents(deposit),
    sections,
  });
}

/** A filename a client can recognise in their downloads folder. */
export function documentFilename(company: string, kind: 'invoice' | 'agreement'): string {
  const slug = company.replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '') || 'bothmade';
  return `${slug}-${kind}.pdf`;
}

/**
 * Both PDFs for one proposal, built concurrently.
 *
 * Neither is allowed to sink the send on its own. An email carrying the
 * agreement but no invoice — or the other way round — is worth far more to
 * the client than a failed send and a rep who finds out tomorrow, so a
 * builder that throws yields null for that attachment and the caller sends
 * what it has.
 */
export async function buildProposalDocuments(input: ProposalDocumentInput): Promise<{
  invoice: Buffer | null;
  contract: Buffer | null;
  failures: string[];
}> {
  const failures: string[] = [];

  const [invoice, contract] = await Promise.all([
    buildInvoiceForProposal(input)
      .then((bytes) => Buffer.from(bytes))
      .catch((error) => {
        console.error('Invoice PDF build failed:', error);
        failures.push('invoice');
        return null;
      }),
    buildContractForProposal(input)
      .then((bytes) => Buffer.from(bytes))
      .catch((error) => {
        console.error('Contract PDF build failed:', error);
        failures.push('agreement');
        return null;
      }),
  ]);

  return { invoice, contract, failures };
}
