-- The answer sheet behind every line item: what it is, what it costs, how to
-- sell it, and why the price is fair.
CREATE TABLE "sales_playbook_items" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "kind" TEXT NOT NULL DEFAULT 'essential',
    "priceCents" INTEGER NOT NULL,
    "whatItIs" TEXT NOT NULL,
    "pitch" TEXT NOT NULL,
    "justification" TEXT NOT NULL,
    "objection" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "sales_playbook_items_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "sales_playbook_items_slug_key" ON "sales_playbook_items"("slug");

-- Seed the playbook. ON CONFLICT DO NOTHING so re-running never overwrites an edited row.
INSERT INTO "sales_playbook_items" ("id","slug","label","kind","priceCents","whatItIs","pitch","justification","objection","updatedAt") VALUES
  (gen_random_uuid()::text, 'websiteredesign', 'Website redesign', 'essential', 120000, 'Rebuilding their site so it looks current and guides a visitor towards getting in touch, instead of just listing information.', 'We''d rebuild the site around one thing: turning the people already finding you into enquiries. Same business, presented the way it deserves.', 'It''s the cheapest item that affects every other one. Better SEO, better ads and better follow-up all still land on the same page — if that page doesn''t convert, everything spent upstream leaks out here.', '"Our site is fine." — Ask what percentage of visitors get in touch. Almost nobody knows, which is the actual problem.', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'mobileoptimisation', 'Mobile optimisation', 'essential', 45000, 'Making the site work properly on a phone — readable text, tappable buttons, fast forms.', 'Most of your customers will find you on a phone, often while they''re standing in the problem. It needs to be effortless on that screen.', 'Typically the majority of traffic is mobile, and Google ranks on the mobile version, not the desktop one. A poor phone experience costs twice — visitors and ranking.', '"It works on my phone." — Ask them to fill in their own enquiry form on it while you wait.', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'servicepagestructure', 'Service-page structure', 'essential', 60000, 'A separate page for each service they offer, instead of one page listing everything.', 'Right now everything you do lives on one page. We''d give each service its own page, so someone searching for that exact thing lands on it.', 'Google can only rank a page for what''s on it. One page covering six services competes weakly for all six; six focused pages compete properly for one each.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'qualifiedenquiryform', 'Qualified enquiry form', 'essential', 40000, 'A form that asks the questions needed to quote, so enquiries arrive complete instead of "call me".', 'We''d have the form ask for what you actually need to quote — so by the time it reaches you, you can price it rather than start a game of phone tag.', 'Every incomplete enquiry costs a call, an email, and a delay. Removing three back-and-forths per enquiry pays for this within weeks.', '"We prefer to talk to them." — You still do. This just means the conversation starts with the details already in hand.', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'bookingorestimateworkflow', 'Booking or estimate workflow', 'essential', 90000, 'Letting customers book a slot or request an estimate online, without ringing.', 'Someone deciding at 9pm can''t ring you. Right now they either wait until morning or ring the next name on the list — and most don''t wait.', 'Out-of-hours enquiries are pure recovered revenue: demand that already exists and is currently lost. It usually only takes one or two recovered jobs to cover this outright.', '"People like to call." — Plenty do, and they still can. This is for the ones who won''t.', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'localseo', 'Local SEO', 'essential', 55000, 'Getting them showing up in the map results and "near me" searches for their area.', 'When someone nearby searches for this, you want to be in that little map box at the top. That''s where the ready-to-buy customers are.', 'Local search traffic is the highest-intent traffic there is — those people are looking to buy now, not researching. It is also the cheapest position to win compared to competing nationally.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'analyticssetup', 'Analytics setup', 'essential', 50000, 'Tracking that shows how many people visit, where they came from, and what they did.', 'At the moment there''s no way to tell which of your marketing actually brings people in. We''d fix that first, so every decision after it is based on something real.', 'It is the smallest item here and it makes every other spend measurable. Without it you cannot tell a campaign that''s working from one that isn''t, so you either keep paying for the wrong thing or cut the right one.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'crmleadrouting', 'CRM lead routing', 'essential', 65000, 'Every enquiry landing in one organised system and going to the right person automatically.', 'Every enquiry lands in one place and goes straight to whoever should handle it, so nothing sits in an inbox over a weekend.', 'One lost enquiry a month is usually worth more than this costs for the year. The value is not the software, it is that follow-up stops depending on somebody remembering.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'professionalcopywriting', 'Professional copywriting', 'essential', 70000, 'Writing the words on the site so they sell, rather than just describe.', 'We''d rewrite the wording so it speaks to what your customers are actually worried about, instead of just listing what you do.', 'The traffic is the expensive part; the words are what convert it. Improving wording lifts results across every visitor you already get, without paying for a single extra one.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'trustandproofsystem', 'Trust and proof system', 'essential', 30000, 'Showing reviews, accreditations, guarantees and real photos of their work where they matter.', 'You''ve got the reputation — it''s just not visible at the moment someone''s deciding. We''d put the proof right where the doubt happens.', 'Cheapest item on the list and often the biggest single lift, because it removes the last hesitation before someone gets in touch. You already own the material; it just is not being used.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'customerportal', 'Customer portal', 'upsell', 200000, 'A private login where customers see their own quotes, jobs, documents and history.', 'Your customers get a login where they can see their quote, their job and their documents — instead of ringing to ask where things are at.', 'Every "where are we up to?" call is unpaid admin. A portal removes that category of call entirely, and makes you look considerably bigger than competitors who cannot offer it.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'reviewautomation', 'Review automation', 'upsell', 70000, 'Automatically asking happy customers for a Google review after a job, and catching unhappy ones privately first.', 'After every completed job it asks for a review automatically — and if someone''s unhappy, it routes them to you privately instead of to Google.', 'Reviews are the single biggest factor in local search and in whether someone picks you. Doing it automatically is the difference between asking occasionally and asking every time.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'smsfollowup', 'SMS follow-up', 'upsell', 60000, 'Automatic text messages for confirmations, reminders and chasing quotes that went quiet.', 'Confirmations, reminders and a nudge on quotes that have gone quiet — by text, automatically.', 'Texts get read almost immediately, unlike email. Cutting no-shows and reviving a fraction of dormant quotes usually covers this several times over.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'onlinepayments', 'Online payments', 'upsell', 90000, 'Taking deposits or full payment through the site.', 'You can take a deposit at the moment they say yes, rather than invoicing and waiting.', 'Getting paid sooner improves cash flow, and a deposit taken at the point of commitment dramatically reduces cancellations. It pays for itself on the timing alone.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'recurringserviceplans', 'Recurring service plans', 'upsell', 120000, 'Selling maintenance or care as a monthly subscription instead of one-off jobs.', 'Instead of chasing the next job, some of your customers pay a set amount monthly for ongoing care — predictable for them and for you.', 'Turns one-off customers into recurring revenue, which is worth several times more per customer over time and makes quiet months survivable.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'emailnurture', 'Email nurture', 'upsell', 85000, 'Automatic email sequences that stay in touch with people who did not buy yet.', 'The ones who aren''t ready today don''t have to be lost — they hear from you occasionally so you''re who they think of when they are ready.', 'Most enquiries do not buy immediately. Without follow-up that work is written off; with it, a slice of it converts months later at no extra acquisition cost.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'paidsearchlandingpages', 'Paid-search landing pages', 'upsell', 90000, 'Dedicated pages built specifically for ad campaigns to point at.', 'If you run ads, they should land somewhere built for that exact search — not on your homepage.', 'Sending paid traffic to a general page wastes a chunk of the ad budget. Purpose-built pages raise the return on money already being spent.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'photoanddocumentuploads', 'Photo and document uploads', 'upsell', 50000, 'Letting customers attach photos or documents to an enquiry.', 'They can send photos of the problem with the enquiry, so you can often quote without a site visit.', 'Every site visit avoided is hours of travel and labour saved. A handful a month makes this trivially worthwhile.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'referralworkflow', 'Referral workflow', 'upsell', 65000, 'A system that makes it easy for happy customers to send you their friends and neighbours.', 'Your happy customers become a channel — it makes referring you a two-tap thing rather than something they mean to do and forget.', 'Referred customers cost nothing to acquire and close far more readily than cold ones. Formalising it turns luck into a reliable stream.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ongoinggrowthplan', 'Ongoing growth plan', 'upsell', 60000, 'A monthly retainer for continued improvements, content and reporting.', 'Rather than build it and leave you, we keep improving it monthly and show you what changed and what it did.', 'A site left alone decays as competitors move and Google changes. Ongoing work protects the investment already made rather than watching it slide.', '"Can we do this later?" — Yes. It is genuinely optional, and better started once results are showing.', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'productledwebsiteredesign', 'Product-led website redesign', 'essential', 350000, 'Rebuilding the site around what buyers are trying to solve, rather than around company structure.', 'We''d reorganise the site around the problems your buyers are trying to solve, so they can find the right product themselves instead of guessing.', 'Technical buyers self-serve most of the way before contacting anyone. If they cannot get there alone, they leave — and you never learn they existed.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'guidedselectionsystem', 'Guided selection system', 'essential', 450000, 'A step-by-step selector that asks the technical questions and narrows buyers to the right product.', 'A buyer answers a few questions about their application and it points them at the right configuration — the conversation your engineers currently have by email, done automatically.', 'It removes the single biggest reason technical buyers abandon: not being sure what fits. It also filters out the enquiries that were never viable, so engineering time goes to the real ones.', '"Our products are too complex for that." — It does not need to give a final answer, only get them close enough to enquire with confidence.', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'structuredrfqwebapp', 'Structured RFQ web app', 'essential', 450000, 'A proper quote-request tool that collects specifications, quantities, deadlines and files up front.', 'Instead of a quote request arriving as a one-line email, it arrives with the specifications, quantities and deadlines already filled in.', 'Your engineers currently spend paid hours collecting information that a form could have gathered. That time is the most expensive in the business and it is being spent on data entry.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'securefileupload', 'Secure file upload', 'essential', 90000, 'Letting buyers attach drawings, parts lists and technical documents to an enquiry safely.', 'They can attach drawings and specifications directly to the enquiry, rather than emailing files around.', 'Quoting cannot start until the drawings arrive. Removing that delay shortens every quote cycle, and handling commercially sensitive files properly is a credibility issue with larger buyers.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'crmintegration', 'CRM integration', 'essential', 120000, 'Enquiries flowing automatically into their sales system as proper opportunities.', 'Every enquiry becomes a tracked opportunity automatically, with the product interest and requirements already attached.', 'Manual re-entry is both a cost and a source of error. Once enquiries land as structured records, you can finally see conversion by product line instead of guessing.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'analyticsandfunneltracking', 'Analytics and funnel tracking', 'essential', 80000, 'Measuring which products get looked at, where buyers give up, and which enquiries turn into orders.', 'You''d see which products get attention, where people give up, and which enquiries actually turn into orders.', 'Small spend, and it is what makes every other investment justifiable. Without it you cannot tell which product lines deserve more marketing and which are quietly losing money.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'technicalseo', 'Technical SEO', 'essential', 90000, 'The behind-the-scenes work that lets Google index and rank a large technical catalogue properly.', 'We make sure Google can actually read and rank your full catalogue, not just the front page.', 'Industrial buyers search in very specific technical language. Ranking for those exact terms attracts a small number of extremely valuable visitors — one order typically dwarfs the cost.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'cmsanddatamigration', 'CMS and data migration', 'essential', 120000, 'Moving existing product data across and giving the team a way to edit it without a developer.', 'Your existing product information comes across properly, and your team can update it themselves afterwards.', 'Without it you are dependent on us for every change, which is slower and more expensive over time. This is the item that stops the site going stale.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'coreintegrations', 'Core integrations', 'essential', 120000, 'Connecting the site to the systems they already run — inventory, email, support, distributors.', 'The site talks to the systems you already run, so information stops being typed into two places.', 'Duplicate entry costs hours and produces numbers that disagree between systems, which means nobody trusts any of them. Connecting them removes both problems at once.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'accessibilityandprivacy', 'Accessibility and privacy', 'essential', 60000, 'Meeting the accessibility and data-protection standards expected of an established commercial business.', 'We bring the site up to the accessibility and data standards your larger customers will expect — and increasingly ask about.', 'Cheap to do at build time and expensive to retrofit. For commercial and public-sector buyers it can be a procurement requirement, so it protects deals rather than just reducing risk.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'quotestatusdashboard', 'Quote-status dashboard', 'upsell', 220000, 'A screen where customers can see whether a quote is under review, quoted, approved or in production.', 'Customers can see exactly where their quote is — under review, quoted, approved, in production — without ringing to ask.', 'Chasing calls consume sales time and irritate the customer doing the chasing. Visibility removes the call and makes you look markedly more professional than competitors who cannot offer it.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'distributororrepportal', 'Distributor or rep portal', 'upsell', 360000, 'A dedicated area for channel partners with their own resources, leads and quoting tools.', 'Your distributors and reps get their own area with the resources, pricing and lead information they need, instead of emailing you for it.', 'Channel partners sell more when they are equipped and self-sufficient. It also removes a steady stream of internal requests that currently interrupt the sales team.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'savedprojectsandboms', 'Saved projects and BOMs', 'upsell', 180000, 'Letting buyers save configurations and parts lists (a BOM is a bill of materials — the list of parts a job needs) to return to later.', 'Engineers can save a configuration or parts list and come back to it, rather than starting from scratch every visit.', 'Technical purchases take weeks and multiple visits. Losing their work between visits is a common reason buyers drift to a competitor whose site remembered them.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'partsandrepeatordering', 'Parts and repeat ordering', 'upsell', 300000, 'Letting existing customers reorder parts or consumables themselves without involving sales.', 'Existing customers can reorder parts themselves, without tying up your sales team on repeat admin.', 'Repeat orders are your highest-margin, lowest-effort revenue and they are currently capped by how many calls your team can answer. Self-service lifts that ceiling entirely.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'serviceandsupportdashboard', 'Service and support dashboard', 'upsell', 240000, 'A place for customers to log service requests and track them through to resolution.', 'Service requests get logged and tracked in one place, so nothing gets lost and customers can see progress.', 'Support handled over email has no record and no accountability. A tracked system reduces repeat contacts and gives you data on which products generate the most service load.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'erporinventoryintegration', 'ERP or inventory integration', 'upsell', 360000, 'Connecting the site to the system that runs stock, orders and production (an ERP is the central business system many manufacturers run on).', 'The site connects to the system that actually runs your stock and orders, so what customers see reflects reality.', 'Stopping quotes on unavailable stock avoids both a bad customer experience and wasted production planning. It is the item that makes everything else trustworthy.', '"Our ERP is old." — Most can still be connected. Worth checking before ruling it out.', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'trainingandresourceplatform', 'Training and resource platform', 'upsell', 180000, 'A structured library of technical documentation, guides and training material.', 'All your technical documentation and guidance in one organised place, rather than scattered across emails and PDFs.', 'Buyers who can self-educate move faster and need less hand-holding. It also reduces the support burden of answering the same technical questions repeatedly.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'automatedlifecyclemessaging', 'Automated lifecycle messaging', 'upsell', 140000, 'Automatic emails triggered by what a customer does — a quote going quiet, a service due, a part needing reordering.', 'Automatic prompts at the right moments — a quote that has gone quiet, a service coming due, parts likely needing reordering.', 'This is revenue you have already earned the right to. Reminding customers at the right moment costs nothing per message and recovers orders that would otherwise simply not happen.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'nativeormultiplatformapp', 'Native or multi-platform app', 'upsell', 600000, 'A proper phone or tablet app, downloaded from the app store, for customers or field staff.', 'A proper app for your field team or customers — works offline, lives on the home screen, built for the job.', 'Only worth it where people work somewhere a browser struggles — on site, offline, in a workshop. Where that is true it is transformative; where it is not, spend the money elsewhere.', '"Do we need an app?" — Be honest. If everything happens at a desk, say no and put the budget into the core build.', CURRENT_TIMESTAMP)
ON CONFLICT ("slug") DO NOTHING;
