-- The answer sheet behind every line item: what it is, what it costs, how to
-- sell it, and why the price is fair.
CREATE TABLE "sales_playbook_items" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "kind" TEXT NOT NULL DEFAULT 'essential',
    "priceCents" INTEGER NOT NULL,
    "whatItIs" TEXT NOT NULL,
    "pitch" TEXT NOT NULL,
    "justification" TEXT NOT NULL,
    "objection" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "sales_playbook_items_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "sales_playbook_items_slug_key" ON "sales_playbook_items"("slug");

-- Seed the playbook. ON CONFLICT DO NOTHING so re-running never overwrites an edited row.
INSERT INTO "sales_playbook_items" ("id","slug","label","kind","priceCents","whatItIs","pitch","justification","objection","updatedAt") VALUES
  (gen_random_uuid()::text, 'websiteredesign', 'Website redesign', 'essential', 120000, 'Rebuilding their site so it looks current and guides a visitor towards getting in touch, instead of just listing information.', 'We''d rebuild the site around one thing: turning the people already finding you into enquiries. Same business, presented the way it deserves.', 'It''s the cheapest item that affects every other one. Better SEO, better ads and better follow-up all still land on the same page — if that page doesn''t convert, everything spent upstream leaks out here.', '"Our site is fine." — Ask what percentage of visitors get in touch. Almost nobody knows, which is the actual problem.', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'mobileoptimisation', 'Mobile optimisation', 'essential', 45000, 'Making the site work properly on a phone — readable text, tappable buttons, fast forms.', 'Most of your customers will find you on a phone, often while they''re standing in the problem. It needs to be effortless on that screen.', 'Typically the majority of traffic is mobile, and Google ranks on the mobile version, not the desktop one. A poor phone experience costs twice — visitors and ranking.', '"It works on my phone." — Ask them to fill in their own enquiry form on it while you wait.', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'servicepagestructure', 'Service-page structure', 'essential', 60000, 'A separate page for each service they offer, instead of one page listing everything.', 'Right now everything you do lives on one page. We''d give each service its own page, so someone searching for that exact thing lands on it.', 'Google can only rank a page for what''s on it. One page covering six services competes weakly for all six; six focused pages compete properly for one each.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'qualifiedenquiryform', 'Qualified enquiry form', 'essential', 40000, 'A form that asks the questions needed to quote, so enquiries arrive complete instead of "call me".', 'We''d have the form ask for what you actually need to quote — so by the time it reaches you, you can price it rather than start a game of phone tag.', 'Every incomplete enquiry costs a call, an email, and a delay. Removing three back-and-forths per enquiry pays for this within weeks.', '"We prefer to talk to them." — You still do. This just means the conversation starts with the details already in hand.', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'bookingorestimateworkflow', 'Booking or estimate workflow', 'essential', 90000, 'Letting customers book a slot or request an estimate online, without ringing.', 'Someone deciding at 9pm can''t ring you. Right now they either wait until morning or ring the next name on the list — and most don''t wait.', 'Out-of-hours enquiries are pure recovered revenue: demand that already exists and is currently lost. It usually only takes one or two recovered jobs to cover this outright.', '"People like to call." — Plenty do, and they still can. This is for the ones who won''t.', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'localseo', 'Local SEO', 'essential', 55000, 'Getting them showing up in the map results and "near me" searches for their area.', 'When someone nearby searches for this, you want to be in that little map box at the top. That''s where the ready-to-buy customers are.', 'Local search traffic is the highest-intent traffic there is — those people are looking to buy now, not researching. It is also the cheapest position to win compared to competing nationally.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'analyticssetup', 'Analytics setup', 'essential', 50000, 'Tracking that shows how many people visit, where they came from, and what they did.', 'At the moment there''s no way to tell which of your marketing actually brings people in. We''d fix that first, so every decision after it is based on something real.', 'It is the smallest item here and it makes every other spend measurable. Without it you cannot tell a campaign that''s working from one that isn''t, so you either keep paying for the wrong thing or cut the right one.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'crmleadrouting', 'CRM lead routing', 'essential', 65000, 'Every enquiry landing in one organised system and going to the right person automatically.', 'Every enquiry lands in one place and goes straight to whoever should handle it, so nothing sits in an inbox over a weekend.', 'One lost enquiry a month is usually worth more than this costs for the year. The value is not the software, it is that follow-up stops depending on somebody remembering.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'professionalcopywriting', 'Professional copywriting', 'essential', 70000, 'Writing the words on the site so they sell, rather than just describe.', 'We''d rewrite the wording so it speaks to what your customers are actually worried about, instead of just listing what you do.', 'The traffic is the expensive part; the words are what convert it. Improving wording lifts results across every visitor you already get, without paying for a single extra one.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'trustandproofsystem', 'Trust and proof system', 'essential', 30000, 'Showing reviews, accreditations, guarantees and real photos of their work where they matter.', 'You''ve got the reputation — it''s just not visible at the moment someone''s deciding. We''d put the proof right where the doubt happens.', 'Cheapest item on the list and often the biggest single lift, because it removes the last hesitation before someone gets in touch. You already own the material; it just is not being used.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'customerportal', 'Customer portal', 'upsell', 200000, 'A private login where customers see their own quotes, jobs, documents and history.', 'Your customers get a login where they can see their quote, their job and their documents — instead of ringing to ask where things are at.', 'Every "where are we up to?" call is unpaid admin. A portal removes that category of call entirely, and makes you look considerably bigger than competitors who cannot offer it.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'reviewautomation', 'Review automation', 'upsell', 70000, 'Automatically asking happy customers for a Google review after a job, and catching unhappy ones privately first.', 'After every completed job it asks for a review automatically — and if someone''s unhappy, it routes them to you privately instead of to Google.', 'Reviews are the single biggest factor in local search and in whether someone picks you. Doing it automatically is the difference between asking occasionally and asking every time.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'smsfollowup', 'SMS follow-up', 'upsell', 60000, 'Automatic text messages for confirmations, reminders and chasing quotes that went quiet.', 'Confirmations, reminders and a nudge on quotes that have gone quiet — by text, automatically.', 'Texts get read almost immediately, unlike email. Cutting no-shows and reviving a fraction of dormant quotes usually covers this several times over.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'onlinepayments', 'Online payments', 'upsell', 90000, 'Taking deposits or full payment through the site.', 'You can take a deposit at the moment they say yes, rather than invoicing and waiting.', 'Getting paid sooner improves cash flow, and a deposit taken at the point of commitment dramatically reduces cancellations. It pays for itself on the timing alone.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'recurringserviceplans', 'Recurring service plans', 'upsell', 120000, 'Selling maintenance or care as a monthly subscription instead of one-off jobs.', 'Instead of chasing the next job, some of your customers pay a set amount monthly for ongoing care — predictable for them and for you.', 'Turns one-off customers into recurring revenue, which is worth several times more per customer over time and makes quiet months survivable.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'emailnurture', 'Email nurture', 'upsell', 85000, 'Automatic email sequences that stay in touch with people who did not buy yet.', 'The ones who aren''t ready today don''t have to be lost — they hear from you occasionally so you''re who they think of when they are ready.', 'Most enquiries do not buy immediately. Without follow-up that work is written off; with it, a slice of it converts months later at no extra acquisition cost.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'paidsearchlandingpages', 'Paid-search landing pages', 'upsell', 90000, 'Dedicated pages built specifically for ad campaigns to point at.', 'If you run ads, they should land somewhere built for that exact search — not on your homepage.', 'Sending paid traffic to a general page wastes a chunk of the ad budget. Purpose-built pages raise the return on money already being spent.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'photoanddocumentuploads', 'Photo and document uploads', 'upsell', 50000, 'Letting customers attach photos or documents to an enquiry.', 'They can send photos of the problem with the enquiry, so you can often quote without a site visit.', 'Every site visit avoided is hours of travel and labour saved. A handful a month makes this trivially worthwhile.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'referralworkflow', 'Referral workflow', 'upsell', 65000, 'A system that makes it easy for happy customers to send you their friends and neighbours.', 'Your happy customers become a channel — it makes referring you a two-tap thing rather than something they mean to do and forget.', 'Referred customers cost nothing to acquire and close far more readily than cold ones. Formalising it turns luck into a reliable stream.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ongoinggrowthplan', 'Ongoing growth plan', 'upsell', 60000, 'A monthly retainer for continued improvements, content and reporting.', 'Rather than build it and leave you, we keep improving it monthly and show you what changed and what it did.', 'A site left alone decays as competitors move and Google changes. Ongoing work protects the investment already made rather than watching it slide.', '"Can we do this later?" — Yes. It is genuinely optional, and better started once results are showing.', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'productledwebsiteredesign', 'Product-led website redesign', 'essential', 350000, 'Rebuilding the site around what buyers are trying to solve, rather than around company structure.', 'We''d reorganise the site around the problems your buyers are trying to solve, so they can find the right product themselves instead of guessing.', 'Technical buyers self-serve most of the way before contacting anyone. If they cannot get there alone, they leave — and you never learn they existed.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'guidedselectionsystem', 'Guided selection system', 'essential', 450000, 'A step-by-step selector that asks the technical questions and narrows buyers to the right product.', 'A buyer answers a few questions about their application and it points them at the right configuration — the conversation your engineers currently have by email, done automatically.', 'It removes the single biggest reason technical buyers abandon: not being sure what fits. It also filters out the enquiries that were never viable, so engineering time goes to the real ones.', '"Our products are too complex for that." — It does not need to give a final answer, only get them close enough to enquire with confidence.', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'structuredrfqwebapp', 'Structured RFQ web app', 'essential', 450000, 'A proper quote-request tool that collects specifications, quantities, deadlines and files up front.', 'Instead of a quote request arriving as a one-line email, it arrives with the specifications, quantities and deadlines already filled in.', 'Your engineers currently spend paid hours collecting information that a form could have gathered. That time is the most expensive in the business and it is being spent on data entry.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'securefileupload', 'Secure file upload', 'essential', 90000, 'Letting buyers attach drawings, parts lists and technical documents to an enquiry safely.', 'They can attach drawings and specifications directly to the enquiry, rather than emailing files around.', 'Quoting cannot start until the drawings arrive. Removing that delay shortens every quote cycle, and handling commercially sensitive files properly is a credibility issue with larger buyers.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'crmintegration', 'CRM integration', 'essential', 120000, 'Enquiries flowing automatically into their sales system as proper opportunities.', 'Every enquiry becomes a tracked opportunity automatically, with the product interest and requirements already attached.', 'Manual re-entry is both a cost and a source of error. Once enquiries land as structured records, you can finally see conversion by product line instead of guessing.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'analyticsandfunneltracking', 'Analytics and funnel tracking', 'essential', 80000, 'Measuring which products get looked at, where buyers give up, and which enquiries turn into orders.', 'You''d see which products get attention, where people give up, and which enquiries actually turn into orders.', 'Small spend, and it is what makes every other investment justifiable. Without it you cannot tell which product lines deserve more marketing and which are quietly losing money.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'technicalseo', 'Technical SEO', 'essential', 90000, 'The behind-the-scenes work that lets Google index and rank a large technical catalogue properly.', 'We make sure Google can actually read and rank your full catalogue, not just the front page.', 'Industrial buyers search in very specific technical language. Ranking for those exact terms attracts a small number of extremely valuable visitors — one order typically dwarfs the cost.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'cmsanddatamigration', 'CMS and data migration', 'essential', 120000, 'Moving existing product data across and giving the team a way to edit it without a developer.', 'Your existing product information comes across properly, and your team can update it themselves afterwards.', 'Without it you are dependent on us for every change, which is slower and more expensive over time. This is the item that stops the site going stale.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'coreintegrations', 'Core integrations', 'essential', 120000, 'Connecting the site to the systems they already run — inventory, email, support, distributors.', 'The site talks to the systems you already run, so information stops being typed into two places.', 'Duplicate entry costs hours and produces numbers that disagree between systems, which means nobody trusts any of them. Connecting them removes both problems at once.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'accessibilityandprivacy', 'Accessibility and privacy', 'essential', 60000, 'Meeting the accessibility and data-protection standards expected of an established commercial business.', 'We bring the site up to the accessibility and data standards your larger customers will expect — and increasingly ask about.', 'Cheap to do at build time and expensive to retrofit. For commercial and public-sector buyers it can be a procurement requirement, so it protects deals rather than just reducing risk.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'quotestatusdashboard', 'Quote-status dashboard', 'upsell', 220000, 'A screen where customers can see whether a quote is under review, quoted, approved or in production.', 'Customers can see exactly where their quote is — under review, quoted, approved, in production — without ringing to ask.', 'Chasing calls consume sales time and irritate the customer doing the chasing. Visibility removes the call and makes you look markedly more professional than competitors who cannot offer it.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'distributororrepportal', 'Distributor or rep portal', 'upsell', 360000, 'A dedicated area for channel partners with their own resources, leads and quoting tools.', 'Your distributors and reps get their own area with the resources, pricing and lead information they need, instead of emailing you for it.', 'Channel partners sell more when they are equipped and self-sufficient. It also removes a steady stream of internal requests that currently interrupt the sales team.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'savedprojectsandboms', 'Saved projects and BOMs', 'upsell', 180000, 'Letting buyers save configurations and parts lists (a BOM is a bill of materials — the list of parts a job needs) to return to later.', 'Engineers can save a configuration or parts list and come back to it, rather than starting from scratch every visit.', 'Technical purchases take weeks and multiple visits. Losing their work between visits is a common reason buyers drift to a competitor whose site remembered them.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'partsandrepeatordering', 'Parts and repeat ordering', 'upsell', 300000, 'Letting existing customers reorder parts or consumables themselves without involving sales.', 'Existing customers can reorder parts themselves, without tying up your sales team on repeat admin.', 'Repeat orders are your highest-margin, lowest-effort revenue and they are currently capped by how many calls your team can answer. Self-service lifts that ceiling entirely.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'serviceandsupportdashboard', 'Service and support dashboard', 'upsell', 240000, 'A place for customers to log service requests and track them through to resolution.', 'Service requests get logged and tracked in one place, so nothing gets lost and customers can see progress.', 'Support handled over email has no record and no accountability. A tracked system reduces repeat contacts and gives you data on which products generate the most service load.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'erporinventoryintegration', 'ERP or inventory integration', 'upsell', 360000, 'Connecting the site to the system that runs stock, orders and production (an ERP is the central business system many manufacturers run on).', 'The site connects to the system that actually runs your stock and orders, so what customers see reflects reality.', 'Stopping quotes on unavailable stock avoids both a bad customer experience and wasted production planning. It is the item that makes everything else trustworthy.', '"Our ERP is old." — Most can still be connected. Worth checking before ruling it out.', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'trainingandresourceplatform', 'Training and resource platform', 'upsell', 180000, 'A structured library of technical documentation, guides and training material.', 'All your technical documentation and guidance in one organised place, rather than scattered across emails and PDFs.', 'Buyers who can self-educate move faster and need less hand-holding. It also reduces the support burden of answering the same technical questions repeatedly.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'automatedlifecyclemessaging', 'Automated lifecycle messaging', 'upsell', 140000, 'Automatic emails triggered by what a customer does — a quote going quiet, a service due, a part needing reordering.', 'Automatic prompts at the right moments — a quote that has gone quiet, a service coming due, parts likely needing reordering.', 'This is revenue you have already earned the right to. Reminding customers at the right moment costs nothing per message and recovers orders that would otherwise simply not happen.', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'nativeormultiplatformapp', 'Native or multi-platform app', 'upsell', 600000, 'A proper phone or tablet app, downloaded from the app store, for customers or field staff.', 'A proper app for your field team or customers — works offline, lives on the home screen, built for the job.', 'Only worth it where people work somewhere a browser struggles — on site, offline, in a workshop. Where that is true it is transformative; where it is not, spend the money elsewhere.', '"Do we need an app?" — Be honest. If everything happens at a desk, say no and put the budget into the core build.', CURRENT_TIMESTAMP)
ON CONFLICT ("slug") DO NOTHING;

-- How each item helps the specific business in front of the rep. Added as a
-- separate step so an already-seeded table picks it up, and only filling
-- blanks so a line edited in the database is never overwritten.
ALTER TABLE "sales_playbook_items" ADD COLUMN IF NOT EXISTS "benefit" TEXT NOT NULL DEFAULT '';

UPDATE "sales_playbook_items" SET "benefit" = 'More of the people already finding {company} turn into actual enquiries. Same marketing, same traffic, more jobs — which is why it comes before spending a penny more on getting found.' WHERE "slug" = 'websiteredesign' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'The customers reaching {company} from a phone — which will be most of them — can actually get in touch without pinching and zooming. It also stops Google quietly ranking {company} lower for a bad phone experience.' WHERE "slug" = 'mobileoptimisation' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Each thing {company} does gets its own page, so someone searching for that exact job finds {company} instead of a competitor who happens to have a page for it.' WHERE "slug" = 'servicepagestructure' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Enquiries arrive at {company} ready to quote instead of as ''call me''. That''s a couple of phone calls saved on every single job, and quotes going out same-day rather than three days later.' WHERE "slug" = 'qualifiedenquiryform' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company} stops losing the evening and weekend enquiries entirely. Those people aren''t waiting until Monday — they''re ringing the next name on the list tonight.' WHERE "slug" = 'bookingorestimateworkflow' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company} shows up in the map results when someone nearby searches. That''s the readiest-to-buy customer there is, and right now they''re finding somebody else.' WHERE "slug" = 'localseo' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company} finally knows which marketing actually produces work. That usually means cutting something that was never paying and putting the money where it does.' WHERE "slug" = 'analyticssetup' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'No enquiry to {company} gets lost in somebody''s inbox again. Following up stops depending on whoever happens to remember.' WHERE "slug" = 'crmleadrouting' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'The words speak to what {company}''s customers are actually worried about, so a bigger share of the same visitors get in touch. It lifts every other thing on this list.' WHERE "slug" = 'professionalcopywriting' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s reviews, guarantees and real job photos appear exactly where someone hesitates. The reputation already exists — this just stops it being invisible at the deciding moment.' WHERE "slug" = 'trustandproofsystem' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s customers can check their own quote, job and paperwork instead of ringing to ask. It removes a whole category of unpaid admin, and makes {company} look considerably bigger than the competition.' WHERE "slug" = 'customerportal' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Every completed job for {company} turns into a review request automatically, and unhappy customers get routed privately first. More reviews means better ranking and an easier sell on every future job.' WHERE "slug" = 'reviewautomation' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Fewer no-shows for {company}, and quotes that went quiet get a nudge without anyone remembering to send it. Texts get read in minutes; emails often don''t get read at all.' WHERE "slug" = 'smsfollowup' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company} takes the deposit the moment someone says yes, rather than invoicing and waiting. Better cash flow, and far fewer people going cold between agreeing and paying.' WHERE "slug" = 'onlinepayments' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Some of {company}''s one-off customers become monthly income. That''s what makes a quiet month survivable and what makes the business worth more if it''s ever sold.' WHERE "slug" = 'recurringserviceplans' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'The enquiries {company} didn''t win aren''t written off — they hear from {company} occasionally, so a slice of them come back later at no extra cost to acquire.' WHERE "slug" = 'emailnurture' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'If {company} runs ads, more of that budget turns into enquiries instead of bouncing off a general page. It makes money already being spent work harder.' WHERE "slug" = 'paidsearchlandingpages' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Customers send photos of the problem with the enquiry, so {company} can often quote without driving out. Every avoided site visit is hours back.' WHERE "slug" = 'photoanddocumentuploads' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s happy customers become a steady source of new ones. Referred work costs nothing to win and closes far more easily than cold enquiries.' WHERE "slug" = 'referralworkflow' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s site keeps improving rather than slowly falling behind, and there''s a monthly report showing what changed and what it did.' WHERE "slug" = 'ongoinggrowthplan' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s buyers can work out what they need themselves, the way technical buyers actually prefer to. Right now the ones who can''t figure it out just leave, and {company} never even knows they existed.' WHERE "slug" = 'productledwebsiteredesign' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'The sizing conversation {company}''s engineers currently have over email happens automatically. Buyers reach the right product with confidence, and engineering time goes to real opportunities instead of tyre-kickers.' WHERE "slug" = 'guidedselectionsystem' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Quote requests reach {company} complete — specifications, quantities, deadlines, drawings — so quoting starts immediately instead of after a week of chasing. Faster quotes win more of them.' WHERE "slug" = 'structuredrfqwebapp' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Drawings and parts lists arrive with the enquiry rather than in a chain of emails, so {company} can start quoting the same day. Handling them properly also matters to bigger buyers doing due diligence.' WHERE "slug" = 'securefileupload' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Every enquiry becomes a tracked opportunity for {company} automatically, with the product interest attached. {company} can finally see conversion by product line instead of guessing at it.' WHERE "slug" = 'crmintegration' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company} sees which products get attention, where buyers give up, and which enquiries become orders — so marketing spend follows the lines that actually sell.' WHERE "slug" = 'analyticsandfunneltracking' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company} gets found for the specific technical terms buyers search. It''s a small number of visitors, but in this industry one of them can be worth more than the entire project.' WHERE "slug" = 'technicalseo' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s team can keep product information current without paying a developer for every change. It''s the item that stops the site going stale in six months.' WHERE "slug" = 'cmsanddatamigration' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s systems stop needing the same information typed into them twice, and the numbers stop disagreeing between them. Less admin, and figures people can actually trust.' WHERE "slug" = 'coreintegrations' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company} meets the standards larger and public-sector buyers increasingly ask about in procurement. Cheap now, expensive to retrofit, and it protects deals rather than just reducing risk.' WHERE "slug" = 'accessibilityandprivacy' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s customers can see where their quote is without ringing to ask. It removes the chasing calls and makes {company} look far more organised than competitors who can''t offer it.' WHERE "slug" = 'quotestatusdashboard' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s distributors and reps get what they need themselves instead of emailing head office. Better-equipped partners sell more, and the internal interruptions stop.' WHERE "slug" = 'distributororrepportal' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Engineers buying from {company} can save a configuration and come back to it. Technical purchases take weeks — losing their work between visits is a common reason they end up buying elsewhere.' WHERE "slug" = 'savedprojectsandboms' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s existing customers reorder parts themselves. That''s the highest-margin revenue there is, and it stops being capped by how many calls the team can answer.' WHERE "slug" = 'partsandrepeatordering' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Service requests to {company} get logged and tracked rather than lost in email, and {company} gets data on which products generate the most support load.' WHERE "slug" = 'serviceandsupportdashboard' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'What {company}''s customers see reflects what''s actually available, so quotes stop going out on stock that isn''t there. It''s what makes everything else on the site trustworthy.' WHERE "slug" = 'erporinventoryintegration' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company}''s buyers can get themselves up to speed without hand-holding, which shortens the sale and cuts the same technical questions being answered over and over.' WHERE "slug" = 'trainingandresourceplatform' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = '{company} gets prompted in front of customers at the moments that matter — a quote gone quiet, a service due, parts likely needing reordering. This is revenue {company} has already earned the right to.' WHERE "slug" = 'automatedlifecyclemessaging' AND "benefit" = '';
UPDATE "sales_playbook_items" SET "benefit" = 'Only worth it if {company}''s people or customers work somewhere a browser struggles — on site, offline, in a workshop. Where that''s true it changes how they work; where it isn''t, that budget belongs in the core build.' WHERE "slug" = 'nativeormultiplatformapp' AND "benefit" = '';
